name: build-with-provenance

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    permissions:
      id-token: write
      attestations: write
      contents: write
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build artifact
        run: |
          mkdir -p bin build/bin dist
          ./scripts/build
          ./scripts/package
          ls -la dist/artifacts/latest
        env:
          CROSS: 1
      - name: Generate SBOM
        uses: anchore/sbom-action@7ccf588e3cf3cc2611714c2eeae48550fbc17552
        with:
          output-file: 'dist/artifacts/latest/rancher-${{github.ref_name}}.spdx.json'
          upload-release-assets: false
          upload-artifact: false
      - name: Attest artifact
        uses: github-early-access/generate-build-provenance@main
        with:
          subject-path: 'dist/artifacts/latest/rancher*'
      - uses: actions/attest-sbom@v1
        with:
          subject-path: 'dist/artifacts/latest/rancher*'
          sbom-path: 'dist/artifacts/latest/rancher-${{github.ref_name}}.spdx.json'
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{github.ref_name}} --generate-notes dist/artifacts/latest/rancher*
