name: Release with SLSA Artifacts
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: {}

jobs:

  sbom:
    permissions:
      contents: write # To upload assets to release.

    runs-on: ubuntu-latest
    steps:
    - uses: anchore/sbom-action@7ccf588e3cf3cc2611714c2eeae48550fbc17552

  # Generate ldflags dynamically.
  args:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ldflags.outputs.version }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          echo "version=$(git describe --tags --always --dirty | cut -c2-)" >> "$GITHUB_OUTPUT"

  # Trusted builder.
  build:
    permissions:
      contents: write # To upload assets to release.
      actions: read # To read the workflow path.

    strategy:
      matrix:
        os-arch:
          - linux-amd64
          - linux-arm64
          - windows-amd64
          - windows-386
          - darwin-amd64
          - darwin-arm64

    needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: 1.21
      config-file: .slsa-goreleaser/${{matrix.os-arch}}.yml
      # Optional: only needed if using ldflags.
      evaluated-envs: "COMMIT_DATE:${{needs.args.outputs.commit-date}}, COMMIT:${{needs.args.outputs.commit}}, VERSION:${{needs.args.outputs.version}}, TREE_STATE:${{needs.args.outputs.tree-state}}"

